apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: waseemakram/two-tier-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              value: admin
            - name: MYSQL_DB
              value: myDb
          volumeMounts:
            - name: message-sql
              mountPath: /docker-entrypoint-initdb.d/message.sql
      volumes:
        - name: message-sql
          hostPath:
            path: /home/ubuntu/task/message.sql  # Replace this with the actual path on your host machine
