apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: two-tier
  template:
    metadata:
      labels:
        app: two-tier
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: 5000
          env:
{{ toYaml .Values.backend.env | indent 12 }}
          volumeMounts:
            - name: message-sql
              mountPath: /docker-entrypoint-initdb.d/message.sql
      volumes:
        - name: message-sql
          hostPath:
            path: {{ .Values.backend.volumePath }}
