apiVersion: v1
kind: Service
metadata:
  name: two-tier
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: two-tier
